local lsp = {
    Array = " ",
    Boolean = "󰨙 ",
    Class = "󰙅 ",
    Constant = "󰏿 ",
    Constructor = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = "󰜢 ",
    File = "󰈙 ",
    Function = "󰊕 ",
    Interface = "󰕘 ",
    Key = "󰌋 ",
    Method = " ",
    Module = " ",
    Namespace = "󰌗 ",
    Null = "󰢤 ",
    Number = "󰎠 ",
    Object = "󰅩 ",
    Operator = "󰆕 ",
    Package = " ",
    Property = " ",
    String = "󰉾 ",
    Struct = "󱡠 ",
    TypeParameter = "󰊄 ",
    Variable = "󰀫 ",
}

local M = {

    ai = {
        copilot = true,
        codecompanion = true,
        supermaven = false,
    },

    code_actions = {
        "",
        "quickfix",
        -- "refactor",
        -- "refactor.extract",
        -- "refactor.inline",
        "refactor.rewrite",
        "source",
        "source.fixAll",
        "source.organizeImports",
    },

    -- Filetypes that should be formatted on save.
    formatting = {
        file_types = {
            bash = { "shellharden", "shfmt" },
            bzl = { "buildifier" },
            caddy = { "caddy" },
            direnv = { "shellharden", "shfmt" },
            fish = { "fish_indent" },
            go = { "goimports", "gofumpt" },
            just = { "just" },
            lua = { "stylua" },
            markdown = { "markdownlint-cli2" },
            pyproject = { "pyproject-fmt" },
            python = { "ruff_organize_imports", "ruff_format", "ruff_fix" },
            sh = { "shellharden", "shfmt" },
            toml = { "taplo" },
            xml = { "xmlformatter" },
        },
        on_save = {
            "bash",
            "caddy",
            "direnv",
            "fish",
            "go",
            "just",
            "lua",
            "rust",
            "toml",
        },
    },

    linters = {
        css = { "stylelint" },
        fish = { "fish" },
        gitcommit = { "commitlint" },
        github = { "actionlint" },
        go = { "revive" },
        markdown = { "markdownlint-cli2", "write_good" },
        nix = { "deadnix", "statix" },
        protobuf = { "protolint" },
        rst = { "rstcheck", "sphinx-lint" },
        text = { "write_good" },
        yaml = { "yamllint" },
    },

    tools = {
        "ghostty-ls",
        "goimports",
        "lemminx",
        "marksman",
        "vtsls",
        "xmlformatter",
    },

    icons = {
        actions = {
            close = "󰅖 ",
            close_box = "󰅗 ",
            close_hexagon = "󰅜 ",
            close_outline = "󰅚 ",
            close_round = "󰅙 ",
        },
        completion_items = {
            Class = lsp.Class,
            Color = "󰏘 ",
            Constant = lsp.Constant,
            Constructor = lsp.Constructor,
            Enum = lsp.Enum,
            EnumMember = lsp.EnumMember,
            Event = " ",
            Field = lsp.Field,
            File = lsp.File,
            Folder = "󰉋 ",
            Function = lsp.Function,
            Interface = lsp.Interface,
            Keyword = lsp.Key,
            Method = lsp.Method,
            Module = lsp.Module,
            Operator = lsp.Operator,
            Property = lsp.Property,
            Reference = "󰋺 ",
            Snippet = "󰩫 ",
            Struct = lsp.Struct,
            Text = " ",
            TypeParameter = lsp.TypeParameter,
            Unit = " ",
            Value = "󰦨 ",
            Variable = lsp.Variable,
            --
            -- Extras that are not part of lsp.CompleteItemKind.
            Code = " ",
            Copilot = " ",
            Supermaven = " ",
            Version = "󱘗 ", -- crates.nvim lsp completion type.
        },
        diagnostics = {
            error = "󰅚",
            warn = "󰀪",
            info = "",
            hint = "󰌶",
            debug = "",
            trace = "",
        },
        fold = {
            open = " ",
            closed = "",
        },
        git = {
            add = "",
            added = "",
            branch = " ",
            conflict = " ",
            deleted = "",
            diff = " ",
            ignore = " ",
            ignored = " ",
            logo = "󰊢 ",
            mod = " ",
            modified = "󰄱", -- aka unstaged
            remove = "",
            rename = " ",
            renamed = "",
            repo = " ",
            staged = " ",
            unmerged = "",
            unstaged = "󰄱 ",
            untracked = "*",
        },
        lsp = lsp,
        markdown = {
            MarkdownH1 = "󰉫 ", -- Used by builtin markdown source
            MarkdownH2 = "󰉬 ",
            MarkdownH3 = "󰉭 ",
            MarkdownH4 = "󰉮 ",
            MarkdownH5 = "󰉯 ",
            MarkdownH6 = "󰉰 ",
        },
        menu = {
            actions = {
                outline = {
                    left = "󰨂",
                    right = "󰨃",
                    up = "󰚷",
                    down = "󰚶",
                    swap = "󰩥",
                    filter = "󱃦",
                },
                filled = {
                    up = "󰍠",
                    down = "󰍝",
                    left = "󰍞",
                    right = "󰍟",
                    swap = "󰩤",
                    filter = "󱃥 ",
                },
            },
            hamburger = "󰍜 ",
            hamburger_open = "󰮫 ",
        },
        misc = {
            ai = "󱚦 ",
            actions = " ",
            arrow_right = "",
            block = "▌",
            bookmark = " ",
            bug = " ", --  '󰠭'
            calendar = " ",
            caret_right = "",
            check = "󰄬 ",
            chevron_right = " ",
            circle = " ",
            circle_filled = " ",
            circle_filled_large = "⬤",
            circle_slash = " ",
            clock = " ",
            code = " ",
            comment = "󰅺 ",
            dashboard = " ",
            datetime = "󱛡 ",
            double_chevron_right = "»",
            down = "⇣",
            ellipse_dbl = "",
            ellipsis = "…",
            exit = "󰗼 ",
            fire = " ",
            gear = " ",
            git = " ",
            github = "󰊤 ",
            history = "󰄉 ",
            hook = "󰛢",
            hook_disabled = "󰛣 ",
            indent = "Ξ",
            kebab = "",
            lightbulb = "󰌶 ",
            line = "", -- 'ℓ'
            list = " ",
            lock = "",
            modified = "●",
            newline = "",
            note = "󰎞 ",
            package = " ",
            pencil = " ", -- '󰏫',
            plus = " ",
            project = " ",
            question = " ",
            quickfix = "󱡠",
            robot = "󰚩 ",
            search = "󰍉 ",
            shaded_lock = " ",
            sign_in = " ",
            surround = "󰗅 ",
            tab = "⇥",
            table = " ",
            tools = " ",
            up = "⇡",
        },
        separators = {
            angle_quote = {
                left = "«",
                right = "»",
            },
            chevron = {
                left = "",
                right = "",
                down = "",
            },
            circle = {
                left = "",
                right = "",
            },
            arrow = {
                left = "",
                right = "",
            },
            slant = {
                left = "",
                right = "",
            },
            bar = {
                left = "⎸",
                right = "⎹",
            },
        },
    },

    -- Various buffer and file types that should be ignored.
    ignored = {
        buffer_types = {
            "gitcommit",
            "health",
            "help",
            "nofile",
            "quickfix",
            "terminal",
            "trouble",
        },
        file_types = {
            "",
            "alpha",
            "bigfile",
            "checkhealth",
            "crates.nvim",
            "git",
            "gitrebase",
            "health",
            "help",
            "lazy",
            "log",
            "mason",
            "noice",
            "notify",
            "oil",
            "qf",
            "snacks_dashboard",
            "snacks_input",
            "snacks_notif",
            "snacks_picker_input",
            "snacks_win",
            "trouble",
            "vim",
        },
        lsp = {
            "copilot",
            "harper-ls",
            "typos_lsp",
        },
        paths = {
            "~/.cache",
            "~/.cargo",
            "~/.local/state",
            "~/.rustup",
            tostring(vim.fn.stdpath("data")),
            tostring(vim.fn.stdpath("state")),
        },
        progress = {
            "basedpyright",
            "copilot",
            "ltex",
            "pylance",
            "pyright",
            "sonarlint.nvim",
        },
    },

    statusline = {
        modes = {
            ["n"] = "N",
            ["no"] = "N",
            ["nov"] = "N",
            ["noV"] = "N",
            ["no"] = "N",
            ["niI"] = "N",
            ["niR"] = "N",
            ["niV"] = "N",
            ["v"] = "V",
            ["V"] = "V",
            [""] = "V",
            ["s"] = "S",
            ["S"] = "S",
            [""] = "S",
            ["i"] = "I",
            ["ic"] = "I",
            ["ix"] = "I",
            ["R"] = "R",
            ["Rc"] = "R",
            ["Rv"] = "R",
            ["Rx"] = "R",
            ["r"] = "R",
            ["rm"] = "R",
            ["r?"] = "R",
            ["c"] = "C",
            ["cv"] = "C",
            ["ce"] = "C",
            ["!"] = "T",
            ["t"] = "T",
            ["nt"] = "T",
        },

        wordcount = {
            markdown = true,
            text = true,
            vimwiki = true,
        },
    },

    ui = {
        border = {
            name = "single",
            chars = { "─", "│", "─", "│", "┌", "┐", "┘", "└" },
        },
        float = {
            border = "single",
            relative = "editor",
            style = "minimal",
            height = 0.75,
            width = 0.8,
            wo = { wrap = true },
        },
    },
}

return M
