-- use({
--     "mfussenegger/nvim-dap",
--     event = "VimEnter",
--     requires = {
--         {
--             "theHamsta/nvim-dap-virtual-text",
--             after = "nvim-dap",
--             config = setup("nvim-dap-virtual-text"),
--         },
--         {
--             "rcarriga/nvim-dap-ui",
--             after = "nvim-dap",
--             config = setup("dapui"),
--         },
--         {
--             "mfussenegger/nvim-dap-python",
--             after = "nvim-dap",
--         },
--         -- "nvim-telescope/telescope-dap.nvim"
--     },
-- },
-- { "jayp0521/mason-nvim-dap.nvim" }
return {}
